# .pre-commit-config.yaml
---
repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.1
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace
